package com.github.bobryanskiy.tamagotchiforlovers.domain.model

enum class PetAlertType {
    HUNGER_WARNING, HUNGER_CRITICAL, HUNGER_DEATH,
    ENERGY_WARNING, ENERGY_CRITICAL, ENERGY_COLLAPSE,
    CLEANLINESS_WARNING, CLEANLINESS_CRITICAL, CLEANLINESS_SICK,
    HAPPINESS_WARNING, HAPPINESS_CRITICAL, HAPPINESS_RUN_AWAY
}