build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  LongMethod:
    active: true
    threshold: 80
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 12
    ignoreDefaultParameters: true
    ignoreDataClasses: true
    ignoreAnnotatedParameter: ['Composable']
  ComplexCondition:
    active: true
    threshold: 5
  TooManyFunctions:
    active: false
  CyclomaticComplexMethod:
    active: true
    threshold: 20

style:
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2', '100', '1000']
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
    ignoreAnnotated: ['Preview', 'Composable']
  MaxLineLength:
    active: true
    maxLineLength: 140
    excludeCommentStatements: true
  WildcardImport:
    active: true
    excludeImports:
      - 'java.util.*'
      - 'kotlinx.coroutines.flow.*'
  ReturnCount:
    active: true
    max: 4
  UnusedPrivateMember:
    active: true
    ignoreAnnotated: ['Preview', 'PreviewLightDark', 'Composable']

naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
    excludeClassPattern: '.*Test'
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][A-Za-z0-9]*'

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true